name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - run: corepack enable
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Lint project
        run: pnpm lint

      - name: ✂️ Knip project
        run: pnpm test:knip

      - name: ⚙️ Check package engines
        run: pnpm test:versions

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - run: corepack enable
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠 Build project
        run: pnpm build

      - name: 💪 Test types
        run: pnpm test:types

      - name: 🧪 Test project
        run: pnpm test:unit -- --coverage

      - name: 🟩 Coverage
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
