name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Lint project
        run: pnpm lint

      - name: ✂️ Knip project
        run: pnpm test:knip

      - name: ⚙️ Check package engines
        run: pnpm test:versions

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠 Build project
        run: pnpm build

      - name: 💪 Test types
        run: pnpm test:types

      - name: 🧪 Test project
        run: pnpm test:unit -- --coverage

      - name: 🟩 Coverage
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
