name: release

permissions: {}

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          runtime: node@latest
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠 Build project
        run: pnpm build

      - name: 📦 Release
        run: pnpm publish --no-git-checks

      - name: 📦 Release alias (stackblitz-clone)
        run: pnpm publish:alias

      - run: pnpm changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
